---
- name: "Gather facts"
  setup: 
  with_items: groups['all']

- name: "Setup Variables"
  set_fact: masterIP="{{ hostvars[item].ansible_host }}"
  with_inventory_hostnames: sparkMaster

- name: "Build /etc/hosts file"
  lineinfile: dest=/etc/hosts regexp='.*{{ item }}$' line="{{ hostvars[item].ansible_host }} {{ item }}" state=present
  with_inventory_hostnames: all

