---
# Install Oracle Java
- name: install add-apt-repository
  apt: name=software-properties-common state=latest
- name: Add Oracle Java Repository
  apt_repository: repo='ppa:linuxuprising/java'
- name: Accept Java 13 License debconf
  debconf: name='oracle-java13-installer' question='shared/accepted-oracle-license-v1-2' value='true' vtype='select'
- name: Accept Java 13 License apt
  apt_key: keyserver=hkp://keyserver.ubuntu.com:80 id=EEA14886
- name: Install Oracle Java 13
  apt:
    name: [oracle-java13-installer, ca-certificates, oracle-java13-set-default]
    state: latest
    update_cache: yes
- name: Install Maven 3
  apt:
    name: maven
    state: latest
    update_cache: yes

- name: Create .m2 directory
  file: dest=/home/{{ user }}/.m2 state=directory
  when: maven_proxy

- name: Make this file on producer
  template: src=settings.xml.j2 dest=/home/{{ user }}/.m2/settings.xml
  when:
    - proxy_id != "not_set"
    - proxy_protocol != "not_set"
    - proxy_user != "not_set"
    - proxy_pass != "not_set"
    - proxy_host != "not_set"
    - proxy_port != "not_set"
    - non_proxy_hosts != "not_set"
    - maven_proxy