---

- name: Create directory protocol statistics
  file: path={{ dir_applications }}/protocols-statistics state=directory mode=0755

- name: Create directory host statistics
  file: path={{ dir_applications }}/host-statistics state=directory  mode=0755

- name: Create directory ddos detection
  file: path={{ dir_applications }}/detection-ddos state=directory mode=0755

- name: Create directory protocol statistics
  file: path={{ dir_applications }}/reflect-ddos state=directory mode=0755



- name: Clone git repository
  git:
     repo: "{{ repository_url }}"
     dest: "{{ repository_tmp }}"
     version: master

- name: Copy protocol statistics
  copy:
    remote_src: True
    src: "{{ repository_tmp }}/applications/statistics/protocols_statistics/spark/protocols_statistics.py"
    dest: "{{ dir_applications }}/protocols-statistics"
    mode: 0755

- name: Copy host statistics
  copy:
    remote_src: True
    src: "{{ repository_tmp }}/applications/statistics/hosts_statistics/spark/host_stats.py"
    dest: "{{ dir_applications }}/host-statistics"
    mode: 0755

- name: Copy ddos detection
  copy:
    remote_src: True
    src: "{{ repository_tmp }}/applications/detection/ddos/spark/detection_ddos.py"
    dest: "{{ dir_applications }}/detection-ddos"
    mode: 0755

- name: Copy ddos reflection
  copy:
    remote_src: True
    src: "{{ repository_tmp }}/applications/detection/reflect_ddos/spark/reflectdos_main.py"
    dest: "{{ dir_applications }}/reflect-ddos"
    mode: 0755
