---
- name: Clone Stream4Flow git repository
  git:
     repo: "{{ repository_url }}"
     dest: "{{ repository_tmp }}"
     version: master

- name: Copy all applications from Stream4Flow git reporsitory
  copy:
    src: "{{ repository_tmp }}/applications/"
    dest: "{{ dir_applications }}/"
    directory_mode: yes
    owner: spark
    group: spark
    mode: 0644
    
- name: Set correct perissions of applications directories
  file:
    path: "{{ dir_applications }}/"
    mode: u=rwX,g=rX,o=rX
    recurse: yes