---
- name: Clone Stream4Flow git repository
  git:
     repo: "{{ repository_url }}"
     dest: "{{ repository_tmp }}"
     version: master

- name: Copy all applications from Stream4Flow git reporsitory
  command: cp -r "{{ repository_tmp }}/applications/." "{{ dir_applications }}/"
    
- name: Set correct owner and permissions of applications
  file:
    dest: "{{ dir_applications }}/{{ item }}"
    owner: spark
    group: spark
    mode: 0644
    recurse: yes
  with_items: ["detection", "statistics", "application_template"]
    
- name: Set correct perissions of applications directories
  file:
    path: "{{ dir_applications }}/"
    mode: u=rwX,g=rX,o=rX
    recurse: yes