- name: "Gather facts"
  setup: 
  with_items: groups['all']

- name: "Setup masterIP variable"
  set_fact: masterIP="{{ hostvars[item].ansible_host }}"
  with_inventory_hostnames: sparkMaster

- name: "Setup producerIP variable"
  set_fact: producerIP="{{ hostvars[item].ansible_host }}"
  with_inventory_hostnames: producer