---
- name: Copy test Data to producer
  copy: src="test-data.ipfix" dest="/tmp/test-data.ipfix"


- name: Send data with ipfixsend
  command: ipfixsend -i /tmp/test-data.ipfix -d {{ producer_ip }} -p {{ producer_port }} -t UDP -n 10

- name: Wait for sending
  pause: seconds=30

