build:
  dir: /tmp/ipfixcol
  git: https://github.com/CESNET/ipfixcol.git
  branch: master
  cmds: [
    autoreconf -i,
    ./configure,
    make,
    make install
  ]
  fastbit:
    archive: libfastbit.tar.gz
    url: https://dior.ics.muni.cz/~velan/libfastbit/
    git: https://github.com/CESNET/libfastbit.git
    dir: /tmp/libfastbit

# this can be easily changed from command line
build_fastbit_compile: false
build_rpms: false

# Set the configuration file path for ipfixcol to load here:
script_path: /usr/local/etc/ipfixcol/
script_filename: startup.xml.udp
