---
# file: roles/kafka/vars/main.yml

kafka_dir: /opt/kafka
kafka_download_url: http://apache.miloslavbrada.cz/kafka/0.10.0.0/kafka_2.11-0.10.0.0.tgz
kafka_filename: kafka_2.11-0.10.0.0
retention: 30000
