- name: Download required Spark packages locally
  include: download_locally.yml

- name: Install dependencies
  include: dependencies.yml
  become: yes

- name: Install Apache Spark and Kafka
  include: install.yml 
  become: yes

- name: Deploy Spark master and slaves service
  include: service.yml
  become: yes
