- name: Create application directory on Master
  file: path={{ dir_applications }} state=directory recurse=yes owner={{ user }} group={{ user }}
  tags:
    - master

- name: Copy the run script to the master
  template: src=run-application.sh.j2 dest={{ dir_applications }}/run-application.sh owner={{ user }} group={{ user }} mode=0750
  tags:
    - master

- name: Copy kafka assembly to the master
  copy: src=/tmp/spark-streaming-kafka-assembly.jar dest={{ dir_spark }}/spark-bin/conf/spark-streaming-kafka-assembly.jar owner={{ user }} group={{ user }}
  tags:
    - master

- name: Install zip on the master
  apt: name=zip state=latest update_cache=yes
  tags:
    - master
