---
# download mirrors
url_spark: "http://apache.miloslavbrada.cz/spark/spark-2.1.0/spark-2.1.0-bin-hadoop2.7.tgz"
url_kafka_assembly: "https://repo1.maven.org/maven2/org/apache/spark/spark-streaming-kafka-assembly_2.11/1.6.3/spark-streaming-kafka-assembly_2.11-1.6.3.jar"

# Name of spark directory after inflating downloaded archive
spark_inflated_dir_name: spark-1.6.2-bin-hadoop2.6

# spark test settings
spark_batch_size: 5000
spark_worker_cores: 2
# spark worker memory in MB
spark_worker_memory: "{{ ansible_memtotal_mb }}"
