---
# Install ELK with dependencies

# Add keys and repositories
- name: add key for elasticsearch
  apt_key: url=https://artifacts.elastic.co/GPG-KEY-elasticsearch
- name: add repository
  apt_repository: repo='deb https://artifacts.elastic.co/packages/5.x/apt stable main'
# Install ELK
- name: install elk and dependencies
  apt: name={{ item }} state=installed
  with_items:
  - elasticsearch
  - kibana
  - logstash
  - python-pip

- name: Install elasticsearch-curator
  pip: "name={{ item }}"
  with_items:
  - elasticsearch-curator
  - argparse

