---
# Install ELK with dependencies

# Add keys and repositories
- name: add key for elasticsearch
  apt_key: url=https://artifacts.elastic.co/GPG-KEY-elasticsearch
- name: add repository elasticsearch
  apt_repository: repo='deb https://artifacts.elastic.co/packages/5.x/apt stable main'
# Install ELK
- name: install elastic
  apt: name=elasticsearch state=installed
- name: install kibana
  apt: name=kibana state=installed
- name: install logstash
  apt: name=logstash state=installed
