---
# Install ELK with dependencies

# Add keys and repositories
- name: add key for elasticsearch
  apt_key: url=https://packages.elastic.co/GPG-KEY-elasticsearch
- name: add repository elasticsearch
  apt_repository: repo='deb http://packages.elastic.co/elasticsearch/2.x/debian stable main'
- name: add repository logstash
  apt_repository: repo='deb http://packages.elastic.co/logstash/2.2/debian stable main'
- name: add repository kibana
  apt_repository: repo='deb http://packages.elastic.co/kibana/4.4/debian stable main'
# Install ELK
- name: install elastic
  apt: name=elasticsearch state=installed
- name: install kibana
  apt: name=kibana state=installed
- name: install logstash
  apt: name=logstash state=installed
