---
# Start and configure Apache Kafka
- name: Ensure zookeper is running
  service: name=zookeeper state=started enabled=yes

- name: Start Kafka server
  service: name=kafka-broker state=started enabled=yes

- name: Wait untill Kafka server starts
  pause: seconds=5

- name: Check if input topic was already added
  shell: /opt/kafka/bin/kafka-topics.sh --list --zookeeper localhost:2181 | grep ipfix.entry
  register: resultin
  failed_when: resultin.rc not in [0,1]

- name: Check if output topic was already added
  shell: /opt/kafka/bin/kafka-topics.sh --list --zookeeper localhost:2181 | grep results.output
  register: resultout
  failed_when: resultout.rc not in [0,1]

- name: Add Kafka topic "ipfix.entry"
  shell: /opt/kafka/bin/kafka-topics.sh --zookeeper localhost:2181 --create --topic ipfix.entry --partitions 1 --replication-factor 1
  when: resultin.rc == 1

- name: Set retention on the input topic
  shell: /opt/kafka/bin/kafka-topics.sh --zookeeper localhost:2181 --alter --topic ipfix.entry --config retention.ms={{ retention }}
  when: resultin.rc == 1

- name: Add Kafka topic "results.output"
  shell: /opt/kafka/bin/kafka-topics.sh --zookeeper localhost:2181 --create --topic results.output --partitions 1 --replication-factor 1
  when: resultout.rc == 1

- name: Set retention on the output topic
  shell: /opt/kafka/bin/kafka-topics.sh --zookeeper localhost:2181 --alter --topic results.output --config retention.ms={{ retention }}
  when: resultout.rc == 1